### ISSUE TITLE
json iframe being inserted when there isn't json on the page

### ISSUE THREAD

**Issue by dscheck** [acrogenesis/jsonview-safari#7] opened 2015-05-21 00:30 UTC
I am seeing the following being inserted on the bottom of some of my pages that have no json in them.

This might have just started with version 1.7
```
<iframe>
#document
<html>
<head>
     <style type="text/css"></style>
</head>
<body>
    <a id="raw" href="https://editedURL?&amp;jsonace=30#raw-json" class="btn btn-default">RAW</a>
    <meta charset="UTF-8">
    <title> editedURL </title>
     <link rel="stylesheet" type="text/css" href="safari-extension://com.acrogenesis.jsonview-56Q494QF3L/8b170976/default.css">
     <div id="json">
           <span class="num">12</span>
     </div>
</body>
</html>
</iframe>
```

**Comment by acrogenesis** [comment] 2015-05-21 00:31
good catch! you are right I hadn't noticed, will fix ASAP. If you can make a PR I'll gladly merge it :+1: .

**Comment by dscheck** [comment] 2015-05-21 01:33
Sorry, I don’t know how to fix it.  I just know that it is happening.

**Comment by acrogenesis** [comment] 2015-05-21 02:40
Don't worry. Do you have an example on a website that this occurs? I can't reproduce the error.

**Comment by acrogenesis** [comment] 2015-05-24 03:34
@dscheck I'm closing this issue but if you do find a website where this happends please re-open it. Also check you have the latest version `1.7`

**Closed by acrogenesis** 2015-05-24 03:34 UTC

**Comment by dscheck** [comment] 2015-05-24 04:51
This was happening with a custom non public dynamic webpage.  

Are there different versions of 1.7?  That sounds odd if so.  

Was anything fixed here or are you saying that you couldn't reproduce?

-dave

**Comment by acrogenesis** [comment] 2015-05-24 08:35
Yeah I didn't explain myself well I meant the latest version was 1.7 (I've just edited my comment). I'm saying I can't reproduce
